apiVersion: v1
kind: Pod
metadata:
  name: ${HELPER_POD}
  namespace: ${K8S_NAMESPACE}
spec:
  restartPolicy: Never
  containers:
    - name: downloader
      image: busybox:latest
      command: ["sleep", "300"]
      volumeMounts:
        - name: results-volume
          mountPath: /data
  volumes:
    - name: results-volume
      persistentVolumeClaim:
        claimName: ${PVC_NAME}
